apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deployment

spec:
  replicas: 1
  selector: 
    matchLabels:
      component: db
  
  template:
    
    metadata:
      labels:
        component: db
    
    spec:
      containers:
      - name: db
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    component: db
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    component: db
