apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 1
  selector: 
    matchLabels:
      component: web
  
  template:
    
    metadata:
      labels:
        component: web
    
    spec:
      containers:
      - name: web
        image: sergiom8m8/as-laboratorio-8-web
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: web-service
  labels:
    component: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    component: web
