name: workflow_main

on: 
  push: 
    branches:
      - main

jobs:
  tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v4

    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_HUB}}

    - name: Build image locally
      run: docker build -t sergiom8m8/as-laboratorio-8-web ./app

    - name: Push image to DockerHub
      run: docker push sergiom8m8/as-laboratorio-8-web

    - name: Authenticate on GCE
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{secrets.GKE_TOKEN}}
        project_id: ${{secrets.GKE_PROJECT}}

    - name: Authenticate on GKE
      uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - name: Set up cluster
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: autopilot-cluster-1
        location: us-central1

    - name: Deploy the web
      run: kubectl apply -f k8s/web-deployment.yaml
      
    - name: Restart the web 
      run: kubectl rollout restart deployment web-deployment

    - name: Deploy the database
      run: kubectl apply -f k8s/db-deployment.yaml
      
    - name: Restart the database 
      run: kubectl rollout restart deployment db-deployment
