name: testing

on: 
  branches:
    - '!main'
    - '*'

jobs:
  tasks:
    runs-on: ubuntu-latest

    steps:
    
    - name: Download repository
      uses: actions/checout@v4

    - name: Testing
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint
