name: workflow_testing

on: 
  push:
    branches:
      - '!main'
      - '*'

jobs:
  tasks:
    runs-on: ubuntu-latest
    permissions:
     security-events: write

    steps:
    
    - name: Download repository
      uses: actions/checout@v4

    - name: Testing
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint
